# Generated by Django 2.2.2 on 2019-06-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_storage_key', models.CharField(max_length=1024)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('file_size', models.IntegerField()),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('datetime_taken', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoResized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_storage_key', models.CharField(max_length=1024)),
                ('md5', models.CharField(max_length=32)),
                ('file_size', models.IntegerField()),
                ('size_label', models.CharField(choices=[('T', 'Thumbnail'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('O', 'Original')], max_length=1)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
    ]
