# Generated by Django 2.2.2 on 2019-06-24 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190624_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
