# Generated by Django 2.2.2 on 2019-06-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190624_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='position',
            new_name='location',
        ),
    ]
