# Generated by Django 2.2.2 on 2019-07-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190624_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.License'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Photographer'),
        ),
    ]
