# Generated by Django 2.2.2 on 2019-07-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='copyright',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Copyright'),
        ),
    ]
