# Generated by Django 2.2.2 on 2019-07-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photo_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Media',
        ),
        migrations.RenameModel(
            old_name='PhotoResized',
            new_name='MediaResized',
        ),
    ]
