# Generated by Django 2.2.2 on 2019-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190723_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('P', 'Photo'), ('V', 'Video')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
