# Generated by Django 2.2.2 on 2019-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190723_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
