# Generated by Django 2.2.2 on 2019-07-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190724_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumresized',
            old_name='media',
            new_name='medium',
        ),
    ]
