# Generated by Django 2.2.2 on 2019-07-24 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190724_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumForPagination',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.medium',),
        ),
        migrations.AddField(
            model_name='medium',
            name='datetime_imported',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediumresized',
            name='datetime_resized',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
