# Generated by Django 2.2.2 on 2019-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190724_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumresized',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
