# Generated by Django 2.2.2 on 2019-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190727_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumresized',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
