# Generated by Django 2.2.2 on 2019-07-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190727_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_storage_key', models.CharField(max_length=1024)),
                ('md5', models.CharField(max_length=32)),
                ('file_size', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MediumForPagination',
        ),
        migrations.CreateModel(
            name='MediumForView',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'constraints': [],
            },
            bases=('main.medium',),
        ),
        migrations.AlterField(
            model_name='medium',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Copyright'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.License'),
        ),
        migrations.AddField(
            model_name='medium',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.File'),
        ),
        migrations.AddField(
            model_name='mediumresized',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.File'),
        ),
    ]
