# Generated by Django 2.2.2 on 2019-07-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_creates_file_model_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='md5',
        ),
    ]
