# Generated by Django 2.2.2 on 2019-08-06 10:35

from django.db import migrations, models

def update_files_bucket(apps, schema_editor):
    Medium = apps.get_model('main', 'Medium')
    MediumResized = apps.get_model('main', 'MediumResized')

    # Constants for File.ORIGINAL or File.PROCESSED don't exist yet
    for row in Medium.objects.all():
        row.file.bucket = "O"
        row.file.save()

    for row in MediumResized.objects.all():
        row.file.bucket = "P"
        row.file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_deletes_mainmedium_md5_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bucket',
            field=models.CharField(choices=[('M', 'Media'), ('P', 'Processed')], default='O', max_length=1),
        ),
        migrations.RunPython(update_files_bucket),
    ]
