# Generated by Django 2.2.2 on 2019-08-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_adds_file_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bucket',
            field=models.CharField(choices=[('O', 'Original'), ('P', 'Processed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='medium',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.File'),
        ),
    ]
