# Generated by Django 2.2.2 on 2019-08-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190806_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumresized',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.File'),
        ),
    ]
