# Generated by Django 2.2.4 on 2019-08-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190806_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bucket',
            field=models.CharField(blank=True, choices=[('O', 'Original'), ('P', 'Processed')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='medium',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.File'),
        ),
        migrations.AlterField(
            model_name='mediumresized',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.File'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
