# Generated by Django 2.2.4 on 2019-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190809_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
