# Generated by Django 2.2.4 on 2019-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190809_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright',
            name='holder',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='photographer',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'importer')},
        ),
    ]
