# Generated by Django 2.2.4 on 2019-09-10 08:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_new_table_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration of the videos, None for photos', null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height of the image/video', null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Location where the photo/video was taken', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='medium',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width of the image/video', null=True),
        ),
        migrations.AlterField(
            model_name='mediumresized',
            name='height',
            field=models.IntegerField(help_text='Height of this resized medium'),
        ),
        migrations.AlterField(
            model_name='mediumresized',
            name='medium',
            field=models.ForeignKey(help_text='Medium that this Resized is from', on_delete=django.db.models.deletion.PROTECT, to='main.Medium'),
        ),
        migrations.AlterField(
            model_name='mediumresized',
            name='width',
            field=models.IntegerField(help_text='Width of this resized medium'),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
