# Generated by Django 2.2.4 on 2019-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_adds_unique_key_tagname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenamedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_renamed', models.DateTimeField()),
            ],
        ),
    ]
