# Generated by Django 2.2.4 on 2019-09-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_renamedtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenamedTag',
            new_name='TagRenamed',
        ),
    ]
