# Generated by Django 2.2.4 on 2019-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_renamedtag2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='importer',
            field=models.CharField(choices=[('X', 'XMP'), ('G', 'Generated'), ('M', 'Manual'), ('R', 'Renamed')], max_length=1),
        ),
    ]
