# Generated by Django 3.1.2 on 2020-10-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_photographer_firstname_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(help_text='ID of this Medium on the remote side')),
                ('api_source', models.IntegerField(choices=[('PROJECT_APPLICATION', 'Project Application')], default='PROJECT_APPLICATION', help_text='Which API this photos was fetched from')),
                ('remote_blob', models.TextField(help_text='Remote information for this Medium. The format depends on the api_source. Kept in case that we need to re-process photos')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.medium')),
            ],
            options={
                'verbose_name_plural': 'RemoteMedia',
            },
        ),
    ]
