# Generated by Django 3.1.2 on 2020-10-08 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remotemedium'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotemedium',
            name='remote_modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Remote modified_on'),
            preserve_default=False,
        ),
    ]
