# Generated by Django 3.1.2 on 2020-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remotemedium_remote_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='spdx_identifier',
            field=models.CharField(blank=True, help_text='Identifier as per https://spdx.org/licenses/ CC-BY-NC-SA-4.0', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='bucket',
            field=models.CharField(choices=[('O', 'Original'), ('P', 'Processed'), ('I', 'Imported')], max_length=1),
        ),
    ]
