# Generated by Django 3.1.2 on 2020-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remote_medium_source_char_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(choices=[('DELETED_MEDIA_LAST_SYNC', 'Deleted Media Last Sync')], max_length=32)),
                ('token_value', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
