# Generated by Django 3.1.2 on 2020-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_synctoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='spdx_identifier',
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(help_text='If it exists: identifier as per https://spdx.org/licenses/ CC-BY-NC-SA-4.0', max_length=255, unique=True),
        ),
    ]
