# Generated by Django 4.1.1 on 2022-12-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_remove_spdx_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="importer",
            field=models.CharField(
                choices=[
                    ("X", "XMP"),
                    ("G", "Generated"),
                    ("M", "Manual"),
                    ("R", "Renamed"),
                    ("I", "Imported"),
                ],
                max_length=1,
            ),
        ),
    ]
