# Generated by Django 4.1.1 on 2022-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_alter_tag_importer"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="image_desc",
            field=models.CharField(
                help_text="Image description", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="medium",
            name="is_image_of_the_week",
            field=models.BooleanField(default=False, help_text="is active"),
        ),
        migrations.AddField(
            model_name="medium",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
