# Generated by Django 4.1.2 on 2023-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_medium_image_desc_medium_is_image_of_the_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medium",
            name="image_desc",
            field=models.CharField(
                help_text="Image description", max_length=1024, null=True
            ),
        ),
    ]
