# Generated by Django 4.1.2 on 2023-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_alter_medium_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="date_archived",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
