# Generated by Django 4.1.2 on 2023-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_medium_date_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="image_comment",
            field=models.CharField(
                help_text="Image comment", max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name="medium",
            name="is_preselect",
            field=models.BooleanField(default=False, help_text="is preselect"),
        ),
    ]
