# Generated by Django 4.1.10 on 2023-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_medium_image_comment_medium_is_preselect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medium",
            name="image_comment",
            field=models.CharField(
                default="", help_text="Image comment", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="medium",
            name="image_desc",
            field=models.CharField(
                default="", help_text="Image description", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="medium",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
    ]
