version: '3.6'

services:
  spi-media-gallery:
    container_name: spi-media-gallery
    build:
      dockerfile: Dockerfile
      context: ./SpiMediaGallery
    secrets:
      - spi_media_gallery_mysql.conf
      - spi_media_gallery_buckets.json
    links:
      - database
    volumes:
      - ${SPI_MEDIA_GALLERY_GPS_SQLITE3_PATH}:/code/gps.sqlite3
      - ./SpiMediaGallery:/code/
      - static_volume:/code/staticfiles
      - tmp-for-spi-media-gallery:/tmp
    expose:
      - "8000"
    networks:
      - nginx-proxy
    env_file:
      - ${SPI_MEDIA_GALLERY_ENV_FILE}
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: spi-media-gallery.django
    restart: unless-stopped

  reverse-proxy:
    container_name: spi-media-gallery-reverse-proxy
    image: nginx:1.19
    secrets:
      - spi_media_gallery_htpasswd
    expose:
      - "1234"
    environment:
      - NGINX_PORT=1234
      - VIRTUAL_HOST=${SPI_MEDIA_GALLERY_DOMAINS}
      - LETSENCRYPT_HOST=${SPI_MEDIA_GALLERY_DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/staticfiles
    links:
      - spi-media-gallery
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: spi-media-gallery.nginx
    restart: unless-stopped

  database:
    container_name: spi-media-gallery-database
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=spi_media_gallery
      - MYSQL_USER=${SPI_MEDIA_GALLERY_DB_USER}
      - MYSQL_PASSWORD=${SPI_MEDIA_GALLERY_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SPI_MEDIA_GALLERY_ROOT_DB_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: spi-media-gallery.mariadb
    restart: unless-stopped

volumes:
  static_volume: {}
  database: {}
  tmp-for-spi-media-gallery:

secrets:
  spi_media_gallery_buckets.json:
    file: ${SPI_MEDIA_GALLERY_BUCKETS_JSON_PATH}
  spi_media_gallery_mysql.conf:
    file: ${SPI_MEDIA_GALLERY_MYSQL_CONF_PATH}
  spi_media_gallery_htpasswd:
    file: ${SPI_MEDIA_GALLERY_HTPASSWD}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
