version: '3.6'

services:
  spi-media-gallery:
    image: spi-media-gallery-docker:0.0.1
    secrets:
      - spi_media_gallery_mysql.conf
      - spi_media_gallery_buckets.json
    volumes:
      - ${SPI_MEDIA_GALLERY_GPS_SQLITE3_PATH}:/code/gps.sqlite3
      - ./SpiMediaGallery:/code/SpiMediaGallery
      - static_volume:/code/SpiMediaGallery/staticfiles
      - tmp-for-spi-media-gallery:/tmp
    expose:
      - "8000"
    networks:
      - nginx-proxy

  reverse-proxy:
    image: nginx:1.17
    secrets:
      - spi_media_gallery_htpasswd
    expose:
      - "1234"
    environment:
      - NGINX_PORT=1234
      - VIRTUAL_HOST=${SPI_MEDIA_GALLERY_DOMAIN}
      - LETSENCRYPT_HOST=${SPI_MEDIA_GALLERY_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/SpiMediaGallery/staticfiles
    links:
      - spi-media-gallery
    networks:
      - nginx-proxy

volumes:
  static_volume: {}
  tmp-for-spi-media-gallery:

secrets:
  spi_media_gallery_buckets.json:
    file: ${SPI_MEDIA_GALLERY_BUCKETS_JSON_PATH}
  spi_media_gallery_mysql.conf:
    file: ${SPI_MEDIA_GALLERY_MYSQL_CONF_PATH}
  spi_media_gallery_htpasswd:
    file: ${SPI_MEDIA_GALLERY_HTPASSWD}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
