version: '3.6'

services:
  spi-media-gallery:
    container_name: spi-media-gallery
    build:
      dockerfile: Dockerfile-dev
      context: ./SpiMediaGallery
    command: python manage.py runserver 0.0.0.0:8000
    secrets:
      - spi_media_gallery_mysql.conf
      - spi_media_gallery_buckets.json
    links:
      - database
    volumes:
      - ./SpiMediaGallery:/code/
      - static_volume:/code/staticfiles
      - tmp-for-spi-media-gallery:/tmp
    ports:
      - "8000:8000"
    env_file:
      - .env

  database:
    container_name: database
    image: mariadb:10.5
    environment:
      - MYSQL_USER=spi
      - MYSQL_PASSWORD=spi
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
      - ./database/mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3000:3306"

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minio minio123;
      mc mb myminio/spi-media-gallery-original;
      mc policy set public myminio/spi-media-gallery-original;
      mc mb myminio/spi-media-gallery-processed
      mc policy set public myminio/spi-media-gallery-processed;
      mc mb myminio/spi-media-gallery-imported
      mc policy set public myminio/spi-media-gallery-imported;
      exit 0;
      "

volumes:
  static_volume:
  database:
  tmp-for-spi-media-gallery:
  minio:

secrets:
  spi_media_gallery_buckets.json:
    file: ./utils/spi_media_gallery_buckets.json
  spi_media_gallery_mysql.conf:
    file: ./utils/project_application_mysql.conf
