version: '3.6'

services:
  spi-media-gallery:
    image: spi-media-gallery-docker:0.0.1
    secrets:
      - spi_media_gallery_mysql.conf
      - spi_media_gallery_buckets.json
    volumes:
      - ./SpiMediaGallery:/code/SpiMediaGallery
      - static_volume:/code/SpiMediaGallery/staticfiles
      - type: tmpfs
        target: /tmp
    expose:
      - "8000"

  reverse-proxy:
    image: nginx:1.17
    ports:
      - 1234:1234
    environment:
      - NGINX_PORT=1234
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - static_volume:/code/SpiMediaGallery/staticfiles
    links:
      - spi-media-gallery

volumes:
  static_volume: {}

secrets:
  spi_media_gallery_buckets.json:
    file: ${SPI_MEDIA_GALLERY_BUCKETS_JSON_PATH}
  spi_media_gallery_mysql.conf:
    file: ${SPI_MEDIA_GALLERY_MYSQL_CONF_PATH}
